config/routes.rb
Rails.application.routes.draw do
  get 'articles/show'

  get 'articles/new'

  resources :users do
    resources :educations, only: [:create]
  end

  resources :articles
  resources :tasks

  root to: "users#user_root"

  # Custom routes
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title,   presence: true,
                      length: { in: 10..255 }

  validates :body,    presence: true,
                      length: { minimum: 20 }


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :fetch_article, only: [:show, :destroy, :edit, :update]
  before_action :check_if_logged_in, only: [:create, :destroy, :update, :edit, :new]

  def show

  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = "Artikel sparades!"
      redirect_to current_user
    else
      flash.now[:danger] = "Artikel kunde inte sparas!"
      render 'new'
    end
  end

  def new
    @article = Article.new
  end

  def destroy
    @article.destroy
    flash[:success] = "Artikeln togs bort!"
    redirect_to articles_path
  end

  def edit
  end

  def update
    if @article.update_attributes(article_params)
      flash[:success] = "Artikeln uppdaterades!"
      redirect_to @article
    else
      flash.now[:danger] = "Artikeln kunde inte uppdateras!"
      render 'edit'
    end
  end

  def index
    @articles = Article.all
  end

  private

    def article_params
      params.require(:article).permit(:title, :body)
    end

    def fetch_article
      @article = Article.find(params[:id])
    end

    def check_if_logged_in
      redirect_to root_path unless logged_in?
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_form.html.erb
<%= tinymce %>

<%= form_for @article do |f| %>
    <%= render 'shared/error_messages', obj: f.object %>
    <div class="form-group">
      <%= f.label :title, "Titel" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <%= f.label :body, "Innehåll" %>
    <%= f.text_area :body, :class => "tinymce", :rows => 40, :cols => 120 %>

    <%= f.submit "Skapa", class: "btn btn-primary" %>
    <%= link_to "Tillbaka", root_path, class: "btn btn-primary" %>
<% end %>

app/views/articles/edit.html.erb
<% content_for :title, "Regigera artikel" %>

<%= render 'article_form' %>

app/views/articles/index.html.erb
<% content_for :title, "Artiklar" %>

<hr />

<ul>
  <%= render 'shared/flash_messages' %>
  <% @articles.each do |article| %>
    <li class="panel panel-primary">
      <div class="panel-heading">
        <%= link_to article.title, article_path(article), class: "panel-title" %>
      </div>
      <div class="panel-body">
        <p><%= truncate(strip_tags(article.body)) %></p>
        <p><%= article.created_at.to_formatted_s(:db) %></p>
      </div>
    </li>
  <% end %>
</ul>

<%= link_to "Tillbaka", root_path, class: "btn btn-primary" %>

app/views/articles/new.html.erb
<% content_for :title, "Ny artikel" %>

<%= render 'article_form' %>

app/views/articles/show.html.erb
<hr />
<%= render 'shared/flash_messages' %>
<div class="panel panel-primary">
   <div class="panel-heading">
     <%= @article.title %>
   </div>
   <div class="panel-body">
     <p><%= @article.body.html_safe %></p>
     <%= link_to "Ta bort", article_path(@article), method: :delete,
                                                    data: { confirm: "Vill du verkligen ta bort artikeln?"}  %>
     <%= link_to "Ändra", edit_article_path(@article) %>
   </div>
 </div>


<%= link_to "Tillbaka", articles_path, class: "btn btn-primary" %>