config/routes.rb
Rails.application.routes.draw do
  get 'articles/show'

  get 'articles/new'

  resources :users do
    resources :educations, only: [:create]
  end

  resources :articles
  resources :tasks

  root to: "users#user_root"

  # Custom routes
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_SSN_REGEX = /\A[0-9]{6}-[0-9]{4}/i
  attr_accessor :remember_token
  has_and_belongs_to_many :tasks
  has_many :articles
  has_many :educations
  has_one :contact_person

  accepts_nested_attributes_for :contact_person

  before_save { self.email = email.downcase }
  before_save { self.full_name = "#{self.first_name} #{self.last_name}" }
  # Detta scope används för fuzzy search (behöver inte vara exakta sökningar)
  scope :search, -> (query) { where "lower(user_name) like ?", "%#{query.downcase}%" }

  validates :user_name,      presence: true,
                             length: { in: 4..100 },
                             uniqueness: true

  validates :first_name,     presence: true,
                             length: { in: 4..100 }

  validates :last_name,      presence: true,
                             length: { in: 4..100 }

  validates :password,       presence: true,
                             length: { in: 6..100 }

  validates :email,          presence: true, length: { maximum: 255 },
                             format: { with: VALID_EMAIL_REGEX },
                             uniqueness: { case_sensitive: false }

  validates :ssn,            presence: true, format: { with: VALID_SSN_REGEX },
                             uniqueness: true;

  validates :phone_number,   presence: true, length: { in: 7..15 }


  has_secure_password

  # Remember me token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # "Kommer ihåg" en användare
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # "Glömmer en användare"
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returnerar hashvärdet av strängparametern
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Kollar en authentication token mot hashen i databasen
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_admin, only: [:new, :create, :destroy, :index]
  before_action :authorize_login, only: [:show, :index, :create, :destroy]

  def new
    @user = User.new
    @user.build_contact_person
  end

  def index
    # Sidindelade användare, 5 användare per sida
    if params[:search]
      @users = User.paginate(:page => params[:page], :per_page => 5).search(params[:search])
    else
      @users = User.paginate(:page => params[:page], :per_page => 5)
    end

    respond_to do |format|
      format.js # index.js.erb
      format.html # intex.html.erb
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Du gav personen sparken, bra jobbat!"
    redirect_to users_path
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Du har registrerat en ny anställd!"

      # Redirect till current user istället för den nya användaren,
      # eftersom det bara är admin som kan skapa profiler
      redirect_to current_user
    else
      render 'new'
    end
  end

  # Redirects to login or current user depending on if you're logged in
  def user_root
    if logged_in?
      redirect_to current_user
    else
      redirect_to login_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :first_name, :last_name, :password, :password_confirmation, :phone_number, :ssn, :email,
                                 contact_person_attributes: [:id, :full_name, :email, :phone_number])
                                 # ^ Nästlade attribut för contact_person
  end

  # Skickar tillbaka ickeadmins till deras profiler eller loginsidan
  # Bra att köra innan saker som bara admin ska få göra
  def check_if_admin
    unless logged_in?
      redirect_to login_path
    else
      unless current_user.admin?
        redirect_to current_user
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_dashboard.html.erb
<div class="btn-group" role="group" aria-label="...">
  <%= link_to "Skapa ny anställd", new_user_path, class: "btn btn-default" %>
  <%= link_to "Visa anställda", users_path, class: "btn btn-default" %>
  <%= link_to "Ny artikel", new_article_path, class: "btn btn-default" %>
  <%= link_to "Visa alla artiklar", articles_path, class: "btn btn-default" %>
  <%= link_to "Lägg till uppgift", new_task_path, class: "btn btn-default" %>
  <%= link_to "Visa uppgifter", tasks_path, class: "btn btn-default" %>
</div>

app/views/users/_education_display.html.erb
<% @user.educations.each do |education| %>
  <div>
    <p><strong><%= education.name %></strong></p>
    <p>Skola: <%= education.school %></p>
    <p>Tog examen: <%= education.graduation.strftime("%F") %></p>
  </div>
<% end %>

app/views/users/_user_display.html.erb
<%= js_will_paginate @users %>

<hr />
<ul class="list-group">
  <% @users.each do |user| %>
    <!-- Visar inte admin..så att admin inte ger admin sparken -->
    <% next if user.admin %>
    <li class="list-group-item">
      <%= link_to user.user_name, user %><%= link_to "Ge sparken", user_path(user), method: :delete, data: { confirm: "Vill du verkligen sparka den här personen?"}, class: "fire-link" %>
    </li>
  <% end %>
</ul>

app/views/users/_user_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', obj: f.object %>
    <div class="form-group">
      <%= f.label :user_name, "Användarnamn" %>
      <%= f.text_field :user_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :first_name, "Förnamn" %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name, "Efternamn" %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :ssn, "Personnummer" %>
      <%= f.text_field :ssn, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number, "Telefonnummer" %>
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :password, "Lösenord" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, "Konfirmera lösenord" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <!-- Kontaktperson -->
    <hr />
    <h3>Närmaste kontaktperson<h3>

    <%=  f.fields_for :contact_person do |ff| %>
      <div class="form-group">
        <%= ff.label :full_name, "Namn" %>
        <%= ff.text_field :full_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= ff.label :phone_number, "Telefonnummer" %>
        <%= ff.text_field :phone_number, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= ff.label :email, "Email" %>
        <%= ff.text_field :email, class: "form-control" %>
      </div>
    <% end %>

    <hr />
    <%= f.submit "Skapa användare", class: "btn btn-primary" %>
    <%= link_to "Tillbaka", root_path, class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<h2>Anställda</h2>

<!-- Sökformulär, sätter params[:search] -->
<div>
  <%= form_tag(users_path, :method => "get", remote: true) do %>
    <!-- Plockar bort params[:search] om queryn är tom.
         Ser fult ut med tomma querys i URL'n.. -->
    <% if params[:search] == "" %>
      <% params.delete :search %>
    <% end %>

    <%= text_field_tag :search, params[:search], :value => params[:search], maxlength: 100, class: "form-control", id: "user-search-field" %>
    <!-- Empty paragrah is filled with the search query via JavaScript -->
    <p id="search-query-placeholder"></p>
    <button type="submit" class="btn btn-primary" id="user-search-index">Sök</button>
    <%= link_to "Rensa sökning", users_path, class: "btn btn-primary" %>
  <% end %>
</div>

<div id="user_display">
  <%= render 'user_display' %>
</div>

<%= link_to "Tillbaka", current_user, class: "btn btn-primary" %>

app/views/users/index.js.erb
$('#user_display').html("<%= j render :partial => 'user_display' %>");

app/views/users/new.html.erb
<% content_for :title, "Registrera" %>

<h1>Registrera ny användare</h1>

<%= render 'user_form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Hantera anställda</h3>
      </div>
      <div class="panel-body">
        <%= render 'shared/flash_messages' %>
        <h2><%= @user.user_name %></h2>
        <h4><%= @user.full_name %></h4>

        <!-- Om användaren är admin renderas views/users/_admin_dashboard.html.erb -->
        <!-- Formulären ska vara gömda, när admin klickar på t.ex ny utbildning ska en flashig jquery animation komma typ-->

        
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#info" aria-controls="info" class="color" role="tab" data-toggle="tab">Personuppgifter</a></li>
          <li role="presentation"><a href="#education" aria-controls="education" class="color "role="tab" data-toggle="tab">Utbildning</a></li>
          <li role="presentation"><a href="#contacts" aria-controls="contacts" class="color" role="tab" data-toggle="tab">Kontaktperson</a></li>
        </ul>
       

        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="info">
            <p>Personnummer: <%= @user.ssn %></p>
            <p>Email: <%= @user.email %></p>
            <p>Telefonnummer: <%= @user.phone_number %></p>
          </div>

          <div role="tabpanel" class="tab-pane" id="education">
            <div id="education-display"><%= render "education_display" %></div>

            <% if current_user.admin? %>
              <button id="show-education-form" class="btn btn-default">Lägg till utbildning</button>
              <div id="education-form">
                <div id="education-errors"></div>
                <%= form_for [@user, @user.educations.build], remote: true do |f| %>
                  <%= f.label :name %>
                  <%= f.text_field :name %> <br /> <!-- remove br and style it !-->

                  <%= f.label :school %>
                  <%= f.text_field :school %><br /><!-- remove br and style it !-->

                  <%= f.label :graduation %>
                  <%= f.date_field :graduation %><br /><!-- remove br and style it !-->

                  <%= f.submit "Konfirmera", class: "btn btn-primary" %>
                  <button type="button" id="hide-education-form" class="btn btn-danger">Avbryt</button>
                <% end %>
              </div>
            <% end %>
          </div>

          <div role="tabpanel" class="tab-pane" id="contacts">
            <% if @user.contact_person.present? %>
              <p>Namn: <%= @user.contact_person.full_name %></p>
              <p>Telefonnummer: <%= @user.contact_person.phone_number %></p>
              <p>Namn: <%= @user.contact_person.email %></p>
            <% end %>
          </div>
        </div>

        <% if current_user.admin? %>
          <hr />

          <% if @user.admin? %>
            <%= render 'admin_dashboard' %>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>