config/routes.rb
Rails.application.routes.draw do
  get 'articles/show'

  get 'articles/new'

  resources :users do
    resources :educations, only: [:create]
  end

  resources :articles
  resources :tasks

  root to: "users#user_root"

  # Custom routes
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/views/layouts/_admin_sidebar.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar collapse sidebar-collapse admin-sidebar"> <!-- before bugtest: class="col-sm-3 col-lg-2 sidebar" -->
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
    </form>

    <ul class="nav menu">
        <li class="active"><a href="#"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a></li>
        <li class="sidebar-header"> Hantera</li>
        <li><a href="#"><svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"></use></svg> Användare</a></li>
        <li><a href="#"><svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg> Nyheter</a></li>
        <li><a href="#"><svg class="glyph stroked table"><use xlink:href="#stroked-table"></use></svg> Tables</a></li>
        <li><a href="#"><svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"></use></svg> Forms</a></li>
        <li><a href="#"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Alerts &amp; Panels</a></li>
        <li><a href="#"><svg class="glyph stroked star"><use xlink:href="#stroked-star"></use></svg> Icons</a></li>
        <li class="parent ">
            <a href="#">
                <span data-toggle="collapse" href="#sub-item-1"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span> Dropdown
            </a>
            <ul class="children collapse" id="sub-item-1">
                <li>
                    <a class="" href="#">
                        <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Sub Item 1
                    </a>
                </li>
                <li>
                    <a class="" href="#">
                        <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Sub Item 2
                    </a>
                </li>
                <li>
                    <a class="" href="#">
                        <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Sub Item 3
                    </a>
                </li>
            </ul>
        </li>
        <li role="presentation" class="divider"></li>
        <li><a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Login Page</a></li>
    </ul>

    <div class="attribution">Template by <a href="http://www.medialoot.com/item/lumino-admin-bootstrap-template/">Medialoot</a>
        <br/><a href="http://www.glyphs.co" style="color: #333;">Icons by Glyphs</a>
    </div>
</div><!--/.sidebar-->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sidebar-collapse"> <!-- before bugtest: class="navbar-toggle collapsed" -->
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><span>intra</span>EV</a>
            <ul class="user-menu">
                <li class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <div class="profile-circle"><%= current_user.first_name[0] %><%= current_user.last_name[0] %></div> <div class="profile-header-name"><%= current_user.first_name %><span class="caret"></span></div> </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Profile</a></li>
                        <li><a href="#"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>
                        <li><%= link_to logout_path, method: "delete" do %>
                              <svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Logga ut
                            <% end %>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.container-fluid -->
</nav>

<% if current_user.admin? %>
    <%= render 'layouts/admin_sidebar' %>
<% else %>
    <%= render 'layouts/user_sidebar' %>
<% end %>

app/views/layouts/_user_sidebar.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar collapse sidebar-collapse user-sidebar"> <!-- before bugtest: class="col-sm-3 col-lg-2 sidebar" -->
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
    </form>

    <ul class="nav menu">
        <li class="active"><a href="#"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a></li>
        <li class="parent sidebar-profile">

            <a href="#">
                <div class="profile-circle-sidebar"><%= current_user.first_name[0] %><%= current_user.last_name[0] %></div>
                
                    <span class="greeting">God morgon</span></br>
                    <span class="username"><%= current_user.first_name %> <%= current_user.last_name %></span>
                
                <span data-toggle="collapse" href="#sub-item-1"><span class="caret"></span></span>
            </a>
            <ul class="children collapse in" id="sub-item-1">
                <li>
                    <a class="user-link" href="#">
                        <svg class="glyph stroked table"><use xlink:href="#stroked-table"></use></svg> Arbetsuppgifter
                    </a>
                </li>
                <li>
                    <a class="user-link" href="#">
                        <svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"></use></svg> Meddelanden
                    </a>
                </li>
                <li>
                    <a class="user-link" href="#">
                        <svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Tidsrapport
                    </a>
                </li>
                <li>
                    <a class="user-link" href="#">
                        <svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"></use></svg> Kalender
                    </a>
                </li>
            </ul>
        </li>
        <li class="sidebar-header"> Verksamheten</li>
        <li><a href="#"><svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"></use></svg> Nyheter</a></li>
        <li><a href="#"><svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg> Målsättning</a></li>
        <li><a href="#"><svg class="glyph stroked table"><use xlink:href="#stroked-table"></use></svg> Processer</a></li>
        <li><a href="#"><svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"></use></svg> Lagar &amp; Regler</a></li>
        <li><a href="#"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Arbetsmiljö</a></li>
        <li><a href="#"><svg class="glyph stroked star"><use xlink:href="#stroked-star"></use></svg> Hållbarhet</a></li>
        <li class="sidebar-header"> Dokument</li>
        <li><a href="#"><svg class="glyph stroked pencil"><use xlink:href="#stroked-male-user"></use></svg> Styrdokument</a></li>
        <li><a href="#"><svg class="glyph stroked pencil"><use xlink:href="#stroked-male-user"></use></svg> Redovisande dokument</a></li>
        <li><a href="#"><svg class="glyph stroked pencil"><use xlink:href="#stroked-male-user"></use></svg> Blanketter</a></li>
    </ul>

    <div class="attribution">Template by <a href="http://www.medialoot.com/item/lumino-admin-bootstrap-template/">Medialoot</a>
        <br/><a href="http://www.glyphs.co" style="color: #333;">Icons by Glyphs</a>
    </div>
</div><!--/.sidebar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=1,initial-scale=1,user-scalable=1" />
  <title>IntraEV <%= yield :title %></title>
  <link href="http://fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
      <!-- Utloggningsknapp bara för inloggade användare -->
      <% if logged_in? %>
      <body data-no-turbolink="true" id="loggedin">
        <!-- <div id="wrapper"> -->
          <%= render 'layouts/navigation' %>

          <div class="col-xs-12 col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
            <div class="row">
              <ol class="breadcrumb">
                <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
                <li class="active">Dashboard</li>
              </ol>
            </div><!--/.row-->

            <!--
              HELPER
              * row - Skapar en rad
              * col-lg-xx - Skapar kolumner. xx är en siffra (max 12)
              * Alla kolumner ska tillsammans vara 12
              * panel panel-primary - skapar boxen
              * panel-heading - skapar headern
              * panel-body - skapar innehållet i boxen
            -->

            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <h1>Dashboard <small>Admin workbench</small></h1>
                </div>
            </div>
            <%= yield %>

            <!-- Debuginformation om params tex, syns bara i developer -->
            <%= debug(params) if Rails.env.development? %>

          </div>

      </body>
      <% end %>

      <% if !logged_in? %>
        <body data-no-turbolink="true" id="login">
          <%= yield %>

          <!-- Debuginformation om params tex, syns bara i developer -->
          <%= debug(params) if Rails.env.development? %>

        </body>
      <% end %>

</html>